name: Deploy Vue App on Release

on:
  release:
    types: [published]
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Create .env file from GitHub Secrets
        run: |
          echo "VUE_APP_API_BASE_URL=${{ secrets.VUE_APP_API_BASE_URL }}" >> .env
          echo "VUE_APP_VERSION=${GITHUB_REF##*/}" >> .env
  
      - name: Install Dependencies
        run: npm install

      - name: Build Vue App
        run: npm run build

      - name: Deploy to Server via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: "dist/*"
          strip_components: 1
          target: ${{ secrets.REMOTE_PATH }}

      - name: Restart Server (Optional)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            sudo systemctl restart nginx 
